cp sPL.ml ../soln-lab06/sPL.ml
cp sPLc.ml ../soln-lab06/sPLc.ml
cp debug.ml ../soln-lab06/debug.ml
cp sPL_type.ml ../soln-lab06/sPL_type.ml
cp sPL_inter.ml ../soln-lab06/sPL_inter.ml
cp sPL_inter1.ml ../soln-lab06/sPL_inter1.ml
cp sPL_inter2.ml ../soln-lab06/sPL_inter2.ml
cp sPL_token.ml ../soln-lab06/sPL_token.ml
cp sPL_parser.ml ../soln-lab06/sPL_parser.ml
cp sPL_lexer.mll ../soln-lab06/sPL_lexer.mll
cp sVM.ml ../soln-lab06/sVM.ml
